### PR TITLE
Fix for unused type in new ethers-v5 codegen

### LINKED ISSUE #721: Unused type in new release
```
'PromiseOrValue' is declared but never used.
```
with `"@typechain/ethers-v5": "10.1.0"` / `"typechain": "8.1.0"`

### PR DESCRIPTION
**Pull request by iainnash**
Fixes #721

### CODE REVIEW

**Comment by joewagner** [comment]
I'm running into an build error. ` error TS6196: 'PromiseOrValue' is declared but never used.`
As far as I can tell this PR would fix the issue.  Any plans to merge and publish this?

**Comment by krzkaczor** [comment]
@iainnash can you fix CI problems?

**Comment by iainnash** [comment]
can take a look later today

**Comment by yorhodes** [comment]
@iainnash @krzkaczor anything I can do to get this merged/

**Comment by krzkaczor** [comment]
@iainnash thanks for this fix and sorry that it took so long to ship.

**Pull request closed without merging**
