### PR TITLE
ethers: add const assertion for exported ABI

### PR DESCRIPTION
**Pull request by kdembler**
Fixes https://github.com/dethcrypto/TypeChain/issues/782

### CODE REVIEW

**Comment by ziad-saab** [comment]
@krzkaczor what would it take to get this merged?

**Comment by kdembler** [comment]
@krzkaczor Could you please take a look? Without this change, projects depending on Typechain bindings will not be able to use `wagmi` 0.7+ in a type-safe way.

**Comment by dennzimm** [comment]
+1

**Comment by royalaid** [comment]
I would also like to echo support for this, it seems to be the easiest way to achieve a nice bridge between wagmi and typechain.

**Review by krzkaczor — APPROVED** [review]

**Comment by krzkaczor** [comment]
Thanks for this @kdembler. It's released as part of:
https://github.com/dethcrypto/TypeChain/releases/tag/%40typechain%2Fhardhat%406.1.5

Sorry that it took a while.

**Pull request merged**
