### PR TITLE
[ethers-v6] Support node16 moduleSuffix in ethers-v6 target

### PR DESCRIPTION
**Pull request by chmanie**
Akin to #840, this PR adds support for ESM (node16) module resolutions (using the `--node16-modules` flag) to the `ethers-v6` target.

### CODE REVIEW

**Comment by chmanie** [comment]
I gotta be honest with you here, I have no idea why this is failing:

```
> typechain --target=ethers-v6 --node16-modules 'abi/*.json'

Successfully generated 5 typings!
../../node_modules/.pnpm/ethers@6.3.0/node_modules/ethers/types/providers/provider-ipcsocket.d.ts(1,23): error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.
```

**Comment by chmanie** [comment]
Just found an issue with this, I think it's not done yet.

**Comment by chmanie** [comment]
OK, now it's fine.

**Comment by krzkaczor** [comment]
Merged as https://github.com/dethcrypto/TypeChain/pull/863 Thanks!

**Pull request closed without merging**
